name: Sync to Public Portfolio
on:
  push:
    branches:
      - master  # Triggers when you push to your private master branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Prepare Files for Public
        run: |
          # 1. Create the folder
          mkdir public_build
          
          # 2. Copy everything EXCEPT public_build itself to avoid infinite loops
          # We use a subshell to safely copy only existing files
          shopt -s extglob
          cp -r !(public_build) public_build/

          # 3. REMOVE the secret items before syncing
          rm -rf public_build/birthday
          rm -rf public_build/MYTOKEN.txt
          
          # 4. Remove the workflow and git history
          rm -rf public_build/.github
          rm -rf public_build/.git

      - name: Push to Public Repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'public_build'
          destination-github-username: 'Ashim-Paudel'
          destination-repository-name: 'ashimp.github.io'
          user-email: 'paudelashim111@gmail.com'
          target-branch: 'main' # Pushes to the public repo's main branch